version: '3.8'

# Development docker-compose with hot reload
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    restart: unless-stopped
    networks:
      - instructor-network

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - instructor-network

networks:
  instructor-network:
    driver: bridge
