services:
  backend:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    restart: unless-stopped
    network_mode: "host"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - PORT=3030
    depends_on:
      - backend
    network_mode: "host"
